export const SIGNIN_START = 'SIGNIN_START'
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNIN_FAIL = 'SIGNIN_FAIL'

export const ROOMMESSAGES_START = 'ROOMMESSAGES_START'
export const ROOMMESSAGES_SUCCESS = 'ROOMMESSAGES_SUCCESS'
export const ROOMMESSAGES_FAIL = 'ROOMMESSAGES_FAIL'

export const ADDMESSAGE_START = 'ADDMESSAGE_START'
export const ADDMESSAGE_SUCCESS = 'ADDMESSAGE_SUCCESS'
export const ADDMESSAGE_FAIL = 'ADDMESSAGE_FAIL'

export const GETROOM_START = 'GETROOM_START'
export const GETROOM_SUCCESS = 'GETROOM_SUCCESS'
export const GETROOM_FAIL = 'GETROOM_FAIL'





